services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: 'trade-journal-backend'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=db
      - DB_NAME=trade_journal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=trader123
    links:
      - db
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: 'trade-journal-client'
    ports:
      - '80:3000'
    links:
      - 'backend:be'
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=trader123
      - POSTGRES_DB=trade_journal
      # this env var is required for healthcheck
      - PGUSER=postgres
    healthcheck:
      # check if db is ready
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/db-init.sql:/docker-entrypoint-initdb.d/1-db-init.sql
volumes:
  db:
    driver: local